/* CRIANDO DATABASE DE EXEMPLO */

CREATE DATABASE LIVRARIA; 

USE LIVRARIA;

create table LIVROS(
   livro varchar(100),
   autor varchar(100),
   sexo char(1),
   paginas int(5),
   editora varchar(30),
   valor float (10,2),
   uf char(2),
   ano int(4)
   
);

desc livros;

/* INSERINDO VALORES */ 

insert into LIVROS values('Cavalheiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78,'RJ',2018);
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150,'RJ',2019);
INSERT INTO LIVROS VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78,'ES',2011);
INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130,'RS',2018);
INSERT INTO LIVROS VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56,'SP',2017);

desc LIVROS;

select * FROM LIVROS;

/* FILTRANDO EXEMPLOS */
SELECT autor, ano 
from livros 
where valor >= 80;

SELECT livro, autor
from livros 
where valor >=80 and uf = 'SP' OR uf = 'RJ';

/* USANDO LIKE e AND */ 

-- autores, seu tipo de sexo, uf quando o tipo de sexo for masculino E o estado começar com a letra 'R'

select autor, sexo, uf
from livros 
where sexo = 'M' and uf LIKE 'R%';

/* COUNT, GROUP BY */

select COUNT(*) AS 'qntd autores', uf
from livros 
group by uf;


/* ---------------------------------------------- DATABASE COMERCIO ----------------------------------------- */ 

CREATE DATABASE COMERCIO; 

SHOW DATABASES; 

USE COMERCIO; 


/* CRIANDO TABELAS */ 


CREATE TABLE CLIENTE(
   IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
   NOME VARCHAR (30) NOT NULL,
   SEXO ENUM ('M', 'F') NOT NULL,
   EMAIL VARCHAR(30) UNIQUE,
   CPF VARCHAR(15) UNIQUE

); 

CREATE TABLE ENDERECO(
   IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
   RUA VARCHAR(30) NOT NULL,
   BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

   FOREIGN KEY (ID_CLIENTE)
   REFERENCES CLIENTE (IDCLIENTE)

);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

--- INFOS --- 
/* ENDERECO  OBRIGATORIO 
CADASTRO DE SOMENTE UM.

TELEFONE - NAO OBRIGATORIO
CADASTRO DE MAIS DE UM (OPCIONAL) */


/* INSERINDO VALORES */ 

INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M','JOAO@IG.COM', '76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');


INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);


/* SELECINANDO NOMES COMEÇANDO POR 'A' NA TABELA CLIENTE*/

SELECT NOME, EMAIL, CPF 
FROM CLIENTE 
WHERE NOME LIKE 'A%';

/* NUMERO TIPO TELEFONE */
SELECT NUMERO 
FROM TELEFONE 
WHERE TIPO = 'CEL'; 

------ JOIN ------ 

/* UTLIZANDO METODO JOIN SIMPLES COM WHERE */ 

SELECT NOME, EMAIL, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO  
WHERE IDCLIENTE = ID_CLIENTE    -- CHAVE PRIMARIA = CHAVE ESTRANGEIRA -- 

/* INNER JOIN e INNER JOIN + WHERE  */ 

SELECT NOME, EMAIL, BAIRRO, CIDADE 
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, EMAIL, BAIRRO, CIDADE 
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE NOME LIKE 'A%';

/* INNER JOIN 3 TABELAS */ 

SELECT c.NOME, c.EMAIL, e.CIDADE, t.NUMERO
FROM CLIENTE AS c  
INNER JOIN ENDERECO e
ON c.IDCLIENTE = e.ID_CLIENTE
INNER JOIN TELEFONE AS t
ON c.IDCLIENTE = t.ID_CLIENTE;

------- UPDATE /ALTER TABLE ------ 

UPDATE CLIENTE 
SET EMAIL = 'CLARA@GMAIL.COM'
WHERE IDCLIENTE = 4 ;

ALTER TABLE CLIENTE 
CHANGE NOME NAME VARCHAR NOT NULL (30);

DESC CLIENTE;